{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "crewai-a2a-server.fullname" . }}
  labels:
    {{- include "crewai-a2a-server.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "crewai-a2a-server.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}